version: '3.8'

services:
  employeemanagement:
    build:
      context: .
      dockerfile: EmployeeManagement/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "server=mysql;port=3306;database=employee_dbdocker;user=root;password=root;TreatTinyAsBoolean=true;"
    ports:
      - "7101:8080"
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    container_name: ems_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: employee_db
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
